name: Build
on:
  schedule:
    - cron: "21 21 * * *"
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  BASE_IMAGE_NAME: "f37-cinnamon-base"
  BASE_IMAGE_DIR: "cinnamon-base"
  EXTRAS_IMAGE_NAME: "f37-common-extras"
  EXTRAS_IMAGE_DIR: "common-extras"
  IDEAPAD_IMAGE_NAME: "f37-lenovo-ideapad"
  IDEAPAD_IMAGE_DIR: "lenovo-ideapad"
  LEGION_IMAGE_NAME: "f37-lenovo-legion"
  LEGION_IMAGE_DIR: "lenovo-legion"
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}


jobs:
  cinnamon-base-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          context: ${{ env.BASE_IMAGE_DIR }}
          containerfiles: ${{ env.BASE_IMAGE_DIR }}/Dockerfile
          image: ${{ env.BASE_IMAGE_NAME }}
          layers: false
          oci: true

      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2.6
        with:
          image: ${{ env.BASE_IMAGE_NAME }}
          tags: "latest"
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
            
  common-extras-build:
    needs: cinnamon-base-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          context: ${{ env.EXTRAS_IMAGE_DIR }}
          containerfiles: ${{ env.EXTRAS_IMAGE_DIR }}/Dockerfile
          image: ${{ env.EXTRAS_IMAGE_NAME }}
          layers: false
          oci: true

      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2.6
        with:
          image: ${{ env.EXTRAS_IMAGE_NAME }}
          tags: "latest"
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

  lenovo-ideapad-build:
    needs: common-extras-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          context: ${{ env.IDEAPAD_IMAGE_DIR }}
          containerfiles: ${{ env.IDEAPAD_IMAGE_DIR }}/Dockerfile
          image: ${{ env.IDEAPAD_IMAGE_NAME }}
          layers: false
          oci: true

      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2.6
        with:
          image: ${{ env.IDEAPAD_IMAGE_NAME }}
          tags: "latest"
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

  lenovo-legion-build:
    needs: common-extras-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          context: ${{ env.LEGION_IMAGE_DIR }}
          containerfiles: ${{ env.LEGION_IMAGE_DIR }}/Dockerfile
          image: ${{ env.LEGION_IMAGE_NAME }}
          layers: false
          oci: true

      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2.6
        with:
          image: ${{ env.LEGION_IMAGE_NAME }}
          tags: "latest"
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
